version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_MULTIPLE_DATABASES=mlflow,detection_results
    ports:
      - "5432:5432"
    volumes:
      # 호스트 시스템의 프로젝트 폴더에 PostgreSQL 데이터 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  ml_services:
    build: 
      context: .
      dockerfile: docker/Dockerfile.ml
    ports:
      - "8888:8888"  # Jupyter
      - "5000:5000"  # MLflow
      - "8080:8080"  # Airflow
    volumes:
      # 프로젝트 폴더를 컨테이너의 workspace에 마운트
      - /home/dblab/haeun/ml/YOLOv9_DeepSORT/:/workspace
      # Airflow 관련 파일들을 프로젝트 폴더에 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/airflow:/opt/airflow
      # MLflow 관련 파일들을 프로젝트 폴더에 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/mlflow:/mlflow
      # 모델 가중치 파일들을 프로젝트 폴더에 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/models:/models
      # 로그 파일들을 프로젝트 폴더에 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/logs:/logs
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - MLFLOW_TRACKING_URI=postgresql+psycopg2://airflow:airflow@postgres:5432/mlflow
      - DETECTION_DB_URI=postgresql+psycopg2://airflow:airflow@postgres:5432/detection_results
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - POSTGRES_DB=detection_results
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      # Superset 설정과 데이터를 프로젝트 폴더에 저장
      - /home/dblab/haeun/ml/YOLOV9_DeepSORT/classify_streaming/superset:/app/superset_home